### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by RobertoUa** [scalacenter/scalafix#1046]

**Comment by SethTisue** [comment]
on the Scalafix site, https://scalacenter.github.io/scalafix/docs/users/installation.html#maven basically just links to https://github.com/evis/scalafix-maven-plugin . Marcelo, would you want a similar link to your repo, or is your WIP still to WIPpy?

**Comment by marcelocenerine** [comment]
Hi @SethTisue . Thanks for asking. I started that project about 1 year ago but had to put it aside after my 2nd daughter was born and I ran out of free time 😆. Last week I joined forces with my colleague @fsanjuan and we resumed development. Since then it has been under active development. Here is the current status:

- The plugin is feature complete (provides more or less the same functionality as the official sbt one)
- We are working on documenting it (https://github.com/cosmicsilence/gradle-scalafix/pull/6), adding tests and trying to catch any potential bugs.
- Build pipeline + Maven Central paperwork are all done but we are holding off the release of the first final version until we get the outstanding pieces completed. For the time being we are publishing beta versions to Bintray which can still be used (there is a section in the README about that). We are hoping to release a final version next week or the week after.

I was planning to update the Scalafix docs to list it alongside of the Maven plugin. Maybe I could do that a bit earlier as you suggested. Let me just get the README reviewed + merged and then I will open a PR for @olafurpg .

We will also announce it on Twitter soon. Any help you could give to spread the word will be very appreciated :)
