### ISSUE TITLE
Allow custom file://rewrites to specify dependencies

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#111]
Following up on a private discussion with @jvican about his experience implementing rewrites in https://github.com/jvican/sbt-migration-rewrites. The sbt-migrator uses coursier, which means the recommended way to ship that rewrite is to
1.  publish the artifacts to maven/bintray
2. build a custom command-line interface with `coursier bootstrap customrewrite,scalafix-cli -f sbt-migrator`
3. run that rewrites by fully-qualified name `sbt-migrator --rewrites scala:foo.SbtMigrator`

If the rewrite could specify the dependency on coursier, those steps would be replaced with instructions to run

```
scalafix --rewrites https://github.com/sbt-migrator/Rewrite.scala
```

I agree this would be nice-to-have. However, I'm not yet sold on adding this feature because I want to avoid creating a scalafix build-tool. I suspect it become tempting add more nifty features like multiple source files, custom scalacOptions or compiler plugins which better belong to proper build tools like sbt/cbt.

**Comment by jvican** [comment]
The idea I had in mind is that dependencies were specified to Scalafix via a top-level annotation called `@dependsOn(deps: Array[String])` that decorates the rewrite file. I was also thinking about plugin features like `setUp` and `tearDown` hooks.
  
I think this is nice to have, though I admit it's probably too niche and specific to the concrete domain I'm doing the rewrites on. This is because:
  
* Rewrites cannot be semantic. Scala Meta does not compile to 2.10.
* Rewrites need contextual information from sbt and I use extra dependencies to get this information and use it to influence the core rewrites.
  
So it's probably something that most of the rewrite authors won't need, and hence not worth it to work on it now. Initially, I thought this could be useful, but I'm going to take a better approach to get the "semantic" information the sbt rewrites need, so this is in no way blocking me.

**Comment by olafurpg** [comment]
Superseded by plugins, #304
