### ISSUE TITLE
cross-build Scalafix for 2.13

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1111]
* First step of #1108

**Comment by joan38** [comment]
Hey,
I wanted to log here that we have [mill-scalafix](https://github.com/joan38/mill-scalafix) a Scalafix plugin for Mill that I'm trying to cross compile with 2.13 since Mill is about to be released for 2.13.
And it has a dependency on [scalafix-cli](https://mvnrepository.com/artifact/ch.epfl.scala/scalafix-cli).

**Comment by olafurpg** [comment]
@joan38 have you tried using the `scalafix-interfaces` module instead of `scalafix-cli`? The `scalafix-interfaces` module provides a Java-only API that is specifically intended to be used by build tools. For example, sbt-scalafix and gradle plugins use only `scalafix-interfaces`.

**Comment by olafurpg** [comment]
Looking at the implementation of mill-scalafix, I see you're already using scalafix-interfaces. To make this work in 2.13, you need to fetch the scalafix-cli_2.12.11 jars and create a custom classloader that is passed to https://github.com/joan38/mill-scalafix/blob/bf3e2eb3490260527a4607124df25e22b4e09615/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L50

You can look at sbt-scalafix for an example how to do this https://github.com/scalacenter/sbt-scalafix/blob/af91dd1ebeae814c10c21aaa471229eaa52a5866/src/main/scala/scalafix/internal/sbt/ScalafixInterfacesClassloader.scala

**Comment by joan38** [comment]
Thanks for the suggestion @olafurpg, it worked!
