### ISSUE TITLE
Make it easier to load an implementation of scalafix.interfaces.Scalafix

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1151]
As discussed in https://github.com/scalacenter/scalafix/pull/1150#issuecomment-638803769, `scalafix-interfaces` should provide (Java) helpers for:
 - coursier resolution/fetch
 - classloading of the correct `scalafix-cli`

The current helper is pretty low-level: https://github.com/scalacenter/scalafix/blob/d4f3b8e2744166115157f5c7cbef308e905332d1/scalafix-interfaces/src/main/java/scalafix/interfaces/Scalafix.java#L71-L83

This will remove the need for custom code in `sbt-scalafix`, `mill-scalafix`, and all other clients.

**Comment by olafurpg** [comment]
FWIW, in Scalafmt we have a `scalafmt-dynamic_2.{11,12,13}` library that is written in Scala and provides an implementation of `scalafix-interfaces` that dynamically loads the correct version of `scalafmt-cli`. Both Metals and IntelliJ use scalafmt-dynamic instead of `scalafix-interfaces`. The benefit of this approach is that scalafmt-interfaces only contains Java interfaces
 and all the logic is implemented in Scala.

**Comment by bjaglin** [comment]
I have a local branch almost ready with a pure Java implementation inside `scalafix-interfaces` (using https://github.com/coursier/interface), which I think is fine. We can discuss once I open the PR!

**Comment by bjaglin** [comment]
Maybe another benefit of aligning the approach is to try to align classloaders so that scalameta can at some point be shared across scalafmt & scalafix somehow?
