### ISSUE TITLE
fix ci-213-windows

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1198]
The GitHub action [started failing on master](https://github.com/scalacenter/scalafix/actions?query=workflow%3ACI+branch%3Amaster) with https://github.com/scalacenter/scalafix/actions/runs/155292713.

Initial investigation by @mlachkar and myself shows that it's a race condition or a combination of factors, as reverting back to Scala 2.13.2 (no matter what the scalameta version is) OR removing other GitHub actions workflows OR adding `println` OR reverting https://github.com/scalacenter/scalafix/pull/1174 make the problem disappear. We have not been able to reproduce the problem locally.

The debug logs added seem to show that the test failure comes from a [double-"crash" of the presentation compiler wrapper resulting in an empty patch](https://github.com/scalacenter/scalafix/blob/v0.9.18/scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala#L91-L104). Adding some logs is sometimes enough to make the problem disappear, although [we observed a "recovered" crash](https://github.com/scalacenter/scalafix/runs/834295929):
```
2020-07-03T12:14:50.0692483Z first attempt failed, retrying...
2020-07-03T12:14:50.1985464Z [info] - test/explicitResultTypes/LocalImplicits.scala (227 milliseconds)
```

**Comment by bjaglin** [comment]
It might be worth digging into https://github.com/scalacenter/scalafix/commit/ba74db38dde7fcdd4971b56b10ec94cb6fef7092 to get some background.

**Comment by mlachkar** [comment]
Good idea.

**Comment by bjaglin** [comment]
@olafurpg maybe you have some idea/context/pointers?

**Comment by olafurpg** [comment]
What was the motivation to close the revert PR? https://github.com/scalacenter/scalafix/pull/1191

The diff in #1181 is a bit problematic because it uses the presentation compiler directly to lookup types of local symbols. Before that change, ExplicitResultTypes rule only inserted types for public members, which I think is a good constraint. The `skipLocalImplicits` configuration option should be removed, I think it was unused before #1181

**Comment by bjaglin** [comment]
To be sure I follow: public members information is coming from SemanticDB, which does not (obviously) provide similar information for local types, so the only way to get that is through`GlobalProxy` which is unsafe because of https://github.com/scalacenter/scalafix/blob/17a187ccc3e8d8a6acb7b57b4e8fb6e254e4ecd5/scalafix-rules/src/main/scala/scala/meta/internal/proxy/GlobalProxy.scala#L10, right?

Interestingly, it was already referenced before the PR, although unused - should we get rid of https://github.com/scalacenter/scalafix/blob/17a187ccc3e8d8a6acb7b57b4e8fb6e254e4ecd5/scalafix-rules/src/main/scala/scala/meta/internal/proxy/GlobalProxy.scala?

**Comment by olafurpg** [comment]
ExplicitResultTypes doesn't use SemanticDB `SymbolInformation`, it uses the Scalameta parser to only compute SemanticDB *global* symbols and then load those symbols with the presentation compiler. It's not possible to use the same approach for local symbols, which is why I think it would be good to revert #1181  and remove the `skipLocalImplicits` config options
