### ISSUE TITLE
Remove Unused depends on -Xmaxwarns on Scala 2.13

### ISSUE THREAD

**Issue by melezov** [scalacenter/scalafix#1264]
The Remove Unused Scalafix rule seems to be attached to the `-Xmaxwarns` scala compiler option.

The documentation of the `-Xmaxwarns` does not seem to reflect that processing will change, only the presentation of the warnings:

    -Xmaxwarns <n> Maximum warnings to print

If the `-Xmaxwarns` is not set, it defaults to 100.
It means that if the unused imports/code is not within these "printed" warnings, it will not have been processed on Scala 2.13

This is a regression from Scala 2.12.x, where this setting did not seem to affect the scalafix rule execution.

Specific versions I'm referring to: Scala 2.13.3/2.12.12

**Comment by mlachkar** [comment]
In fact the rule RemoveUnusued depends on this parameter, but I don't know what we can do to change this behavior. 
We can document this setting that impact removeUnusued and all rules that depends on Warn messages. 
@bjaglin 
1 - Could we modify the default value on the project where the scalafix plugin is enabled , or just during the run of scalafix, as we do for `-Xfatal-warning` 
2- Report as warning in `withConfiguration` for RemoveUnusued that this value could be increased ?

**Comment by bjaglin** [comment]
1 - That looks like a good idea indeed to leverage https://github.com/scalacenter/sbt-scalafix/pull/196, although I am not sure what's a good value?
2 - This looks like something https://github.com/scalacenter/scalafix/issues/1199 could signal. Since we have the `scalacOptions`, we know the value of `-Xmaxwarns` (implicit default or explicit), so provided all warnings are reported as diagnostics in semanticdb, we could even fail the build when we detect that we have exactly as many diagnostics as the maximum number of warns, since there is a good chance we are missing out some.

**Comment by mlachkar** [comment]
Actually after thinking more seriously about this, semanticdb should not depend on this to record warnings. I m working on a fix on scalemeta side. Those parameters are supposed to change the number of warning or errors printed.

**Comment by mlachkar** [comment]
linked to https://github.com/scalameta/scalameta/pull/2402

**Comment by mlachkar** [comment]
RemoveUnused doesn't depend on Maxwarn anymore!
Thanks for reporting this issue
