### ISSUE TITLE
missing setup for semanticdb compiler plugin not properly detected when overriding scalacOptions

### ISSUE THREAD

**Issue by jtjeferreira** [scalacenter/scalafix#1306]
How to reproduce:

* checkout the code of this PR: https://github.com/mongodb/mongo-scala-driver/pull/74
* add `addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.24")` to plugins.sbt
* scalafixEnable wont set scalacOptions properly:

```
sbt:mongo-scala> project mongo-scala-bson
[info] set current project to mongo-scala-bson (in build file:/home/joao/git/mongo-scala-driver/)
sbt:mongo-scala-bson> show scalacOptions
[info] * -unchecked
[info] * -deprecation
[info] * -feature
[info] * -Ywarn-dead-code
[info] * -language:existentials
[info] * -Xlint:-missing-interpolator
[success] Total time: 0 s, completed Dec 22, 2020, 11:57:24 AM
sbt:mongo-scala-bson> show compile:scalacOptions
[info] * -unchecked
[info] * -deprecation
[info] * -feature
[info] * -Ywarn-dead-code
[info] * -language:existentials
[info] * -Xlint:-missing-interpolator
[success] Total time: 0 s, completed Dec 22, 2020, 11:57:26 AM
sbt:mongo-scala-bson> show test:scalacOptions
[info] * -unchecked
[info] * -deprecation
[info] * -feature
[info] * -Xlint:-missing-interpolator,_
[info] * -Xcheckinit
[success] Total time: 0 s, completed Dec 22, 2020, 11:57:31 AM
sbt:mongo-scala-bson> scalafixEnable
[info] set current project to mongo-scala-bson (in build file:/home/joao/git/mongo-scala-driver/)
sbt:mongo-scala-bson> show scalacOptions
[info] * -Yrangepos
[info] * -Xplugin-require:semanticdb
[success] Total time: 0 s, completed Dec 22, 2020, 11:57:45 AM
sbt:mongo-scala-bson> show compile:scalacOptions
[info] * -unchecked
[info] * -deprecation
[info] * -feature
[info] * -Ywarn-dead-code
[info] * -language:existentials
[info] * -Xlint:-missing-interpolator
[success] Total time: 0 s, completed Dec 22, 2020, 11:57:49 AM
sbt:mongo-scala-bson> show test:scalacOptions
[info] * -unchecked
[info] * -deprecation
[info] * -feature
[info] * -Xlint:-missing-interpolator,_
[info] * -Xcheckinit
[success] Total time: 0 s, completed Dec 22, 2020, 11:57:59 AM
```

this is happening because scalacOptions are being set with `:=` instead of `++=` (https://github.com/mongodb/mongo-scala-driver/pull/74/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R42-R44)
```
scalacOptions in Compile := scalacOptionsVersion(scalaVersion.value),
scalacOptions in Test := scalacOptionsTest,
scalacOptions in IntegrationTest := scalacOptionsTest,
```

If they are changed to use `++=` it works...

**Comment by bjaglin** [comment]
Thanks for the repro and the analysis!

Not sure what to do here, as using `:=` effectively cancels the effect of any plugin since the user settings are applied last (and in that particular case [the options added by sbt for compiler plugins](https://github.com/sbt/sbt/blob/7e1cc051f6f26945a6ad2db7532160b65f8a5b1f/main/src/main/scala/sbt/Defaults.scala#L3897-L3907)), so it's definitely not recommended to do that.

The best we can do is to trigger a more explicit error - maybe by checking for the presence of `-Xplugin.*semanticdb.*` in `scalacOptions` in https://github.com/scalacenter/sbt-scalafix/blob/master/src/main/scala/scalafix/internal/sbt/SemanticRuleValidator.scala? But I am not sure it's worth it as it captures a very specific corner case.

**Comment by bjaglin** [comment]
Actually, there is nothing a command cannot do - `scalafixEnable` should work on all setups. I have sent in https://github.com/scalacenter/sbt-scalafix/pull/203 to fix that.
