### ISSUE TITLE
Make NoAutoTupling work with Function1

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#147]
See the discussion [here](https://github.com/scalacenter/scalafix/pull/143#issuecomment-299592113) and [here](https://github.com/scalacenter/scalafix/pull/143#discussion_r115117022).

The failing cases (rewrite not applied) are

```scala
def f: (((Int, String)) => ((String, List[Int])) => Int) = a => b => a._1
f(1, "")("a", Nil)
```

and 

```scala
val f = (a: (Int, Boolean)) => a
f(2, true)
```

~This is currently blocked by https://github.com/scalameta/scalameta/issues/837~

We can tackle this in two ways:
- by reading denotations #194 (currently blocked by https://github.com/scalameta/scalameta/issues/930)
- by reading compiler messages (blocked by imprecise positions in errors emitted by Scalameta)

**Comment by olafurpg** [comment]
I just realized that this is still an issue when the Function1 is defined in a 3rd party library, a minimal repro is here https://github.com/scalacenter/scalafix/commit/112a3551f1a602cf160bf38aa804a16afec6afce

The problem happens when we don't have access to the denotation. We currently only store denotations for symbols compiled with the Scalahost compiler plugin enabled. I think we should keep this issue open. I believe a long-term solution to this issue would be to use reported compiler warnings, as proposed #194.

**Comment by gabro** [comment]
Right, I'll investigate further on the subject, but I think we'll need a scalameta "hack" to get the caret positions of those messages.

**Comment by olafurpg** [comment]
Yeah, we can accommodate on the Scalameta side to make the positions of the reported messages more accurate.

**Comment by olafurpg** [comment]
Seems https://github.com/scalameta/scalameta/issues/930 is a go, which means we will store the denotations for all used symbols per .semanticdb file.

**Comment by gabro** [comment]
Cool! I still think compiler messages would be much more accurate than any name/denotation based approach, but that feature is certainly going to help in the future.

**Comment by olafurpg** [comment]
Is this fixed now that we use messages?

**Comment by gabro** [comment]
Yes!
