### ISSUE TITLE
Allow to run scalafix on ammonite files or worksheet files

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1534]
semanticdb files are produced and we should be able to run scalafix on ammonite script or worksheets

**Comment by tgodzik** [comment]
For worksheets, we produce semanticdb in-memory and I think it might be hard to do outside Metals or Intellij worksheets.

As for ammonite I think it's only produced in the ammonite runner, otherwise we would need to add it to the magic imports.

I think we can handle both in Metals, do we need to add something in Scalafix itself? Is `.sc` extension not allowed ?
