### ISSUE TITLE
Publish for Scala 2.12.18 and 2.13.11, please?

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scalafix#1770]
2.12.18 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-12-18-release-planning/6089/9

2.13.11 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088/11

**Comment by bjaglin** [comment]
Thanks for the ping. If I understand correctly, 2.13.11 is due tomorrow so I am waiting for that.

**Comment by bradley-marker-ck** [comment]
Will this just build 2.12.18 and not 2.12.17? If so, can we get a patch tagged before this is merged. There are a number of merges since v0.10.4 including a fix I'd like on 2.12.17.

Or if those publish instructions are for the public, I'd be willing to try to tag the specific hash I want with the semanticDb change.

**Comment by bmarker** [comment]
Will this just build 2.12.18 and not 2.12.17? If so, can we get a patch tagged before this is merged. There are a number of merges since v0.10.4 including a fix I'd like on 2.12.17.

Or if those publish instructions are for the public, I'd be willing to try to tag the specific hash I want with the semanticDb change.

**Comment by bjaglin** [comment]
Support merged, release 0.11.0 to be cut within a few hours

**Comment by bjaglin** [comment]
And it's now on Maven central.
