### ISSUE TITLE
Please publish for Scala 2.12.19 and 2.13.13

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scalafix#1936]
...which is now on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-12-19-release-planning/6216/13

**Comment by bjaglin** [comment]
Pending https://github.com/scalameta/scalameta/issues/3573 for semanticdb-scalac support.

A new scalafix release testing full compatibility will follow shortly (using, as well as supporting 2.13.13 also).

Note however that one could most likely use an existing sbt-scalafix release:
* transparently if semanticdb-scalac is backpublished for [4.8.10](https://github.com/scalacenter/scalafix/blob/v0.11.1/project/Dependencies.scala#L31)
* otherwise by following the supposedly actionnable error message added in https://github.com/scalacenter/sbt-scalafix/pull/369

**Comment by SethTisue** [comment]
> transparently if semanticdb-scalac is backpublished for [4.8.10](https://github.com/scalacenter/scalafix/blob/v0.11.1/project/Dependencies.scala?rgh-link-date=2024-02-21T20%3A25%3A31Z#L31)

perhaps that's actually the plan? you could ask on https://github.com/scalameta/scalameta/issues/3573

I'm publishing 2.13.13 to Maven Central right now

**Comment by SethTisue** [comment]
broadened to include 2.13.13, which is now on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-13-release-planning/6315/17?u=sethtisue

**Comment by tgodzik** [comment]
I backpublished Scala 2.12.19 for 4.8.10, 4.8.15 and 4.9.0. Let me know, if anything more is needed!

**Comment by SethTisue** [comment]
not as far as I'm concerned! thanks

**Comment by SethTisue** [comment]
Oh, oops, what about 2.13.13...?

**Comment by tgodzik** [comment]
That's ongoing :sweat_smile:

**Comment by tgodzik** [comment]
Done with Scala 2.13.13 for 4.7.8, 4.8.10, 4.8.15 and 4.9.0.

**Comment by bjaglin** [comment]
Thanks @tgodzik!

Impact of back-publishing validated through https://github.com/scalacenter/sbt-scalafix/pull/389 & https://github.com/scalacenter/sbt-scalafix/pull/390 :+1:

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-testkit_2.13.13/
- https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-testkit_2.12.19/

`scalafix-testkit` for Scala 2.13.13 and 2.12.19 does not available 😢

**Comment by bjaglin** [comment]
> * https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-testkit_2.13.13/
> 
>     * https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-testkit_2.12.19/
> 
> 
> `scalafix-testkit` for Scala 2.13.13 and 2.12.19 does not available 😢

That's right, sorry for the confusion as this focused on supporting target files compiled with 2.12.19 & 2.13.13. I will update the title to be clearer.

The ability for rule authors build against these patches versions was merged in https://github.com/scalacenter/scalafix/pull/1932, but because there is no backpublishing mechanism in Scalafix, it will only have effect in the upcoming Scalafix release (0.12.0), which is blocked by the release Scalameta 4.9.1 for a different reason (4.9.0 had a regression, which I identified by [running a sanity check against your rules actually](https://github.com/bjaglin/scalafix-rules/pull/1)). This should be only a few days away.
