### ISSUE TITLE
Illegal start of sume expression for "\n???"

### ISSUE THREAD

**Issue by strokyl** [scalacenter/scalafix#1953]
Scalafix 0.12.0 suffer from this bug of scalameta
[Illegal start of sume expression for "\n???"](https://github.com/scalameta/scalameta/issues/3571)

**Comment by bjaglin** [comment]
Thanks for reporting this regression!

For traceability, the Scalameta 4.9.1 ticket is https://github.com/scalameta/scalameta/issues/3605, to be fixed by https://github.com/scalameta/scalameta/pull/3606.

There is no workaround possible unfortunately, so users affected by this will need to wait for a new patch release of Scalafix containing a patch release of Scalameta to upgrade to 0.12.x.

**Comment by bjaglin** [comment]
Until a new patch release is cut, users affected by this can use [the latest scalafix-interfaces SNAPSHOT](https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot) (or scalafix-cli of the same version).
