### ISSUE TITLE
Group imports from the same package

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#199]
```scala
// before
import scala.concurrent.Future
import scala.concurrent.{ ExecutionContext => EC }

// after
import scala.concurrent.{ Future, ExecutionContext => EC }
```

This is a rule suggested by Codacy and it should be easy enough to rewrite it automatically.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a faster pace. As long as a custom rule meet a certain level of quality, it can still 

- be automatically be included by `sbt-scalafix`
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
