### ISSUE TITLE
NoAutoTupling rewrite to broken code

### ISSUE THREAD

**Issue by xuwei-k** [scalacenter/scalafix#207]
#### .scalafix.conf

```
rewrites = [NoAutoTupling]
```

#### project/plugins.sbt

```scala
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.4.2")
```

#### build.sbt

```scala
scalaVersion := "2.11.11"
```

#### Main.scala

```scala
object X {
  def foo(a: (Int, Boolean), b: Int): Unit = {}
}

object Main {
  val a = (1, false)
  val z = X.foo(a, 2)
}
```

execute `sbt scalafix compile`

## problem

```diff
--- a/src/main/scala/Test.scala
+++ b/src/main/scala/Test.scala
@@ -4,5 +4,5 @@ object X {
 
 object Main {
   val a = (1, false)
-  val z = X.foo(a, 2)
+  val z = X.foo((a, 2))
 }
```

```
src/main/scala/Test.scala:7: not enough arguments for method foo: (a: (Int, Boolean), b: Int)Unit.
[error] Unspecified value parameter b.
[error]   val z = X.foo((a, 2))
[error]                ^
[error] one error found
```

**Comment by gabro** [comment]
Oh, that's definitely unexpected! Thanks for reporting @xuwei-k, I'll take a look

**Comment by gabro** [comment]
Ok, I found the issue and it's due to my naive parsing of JVM signatures of methods.

Unfortunately there's no obvious way of inferring the number of parameter lists of a JVM signature.

This method:

```scala
def foo(a: (Int, Boolean), b: Int)(s: String): Unit = {}
```

is encoded into:

```scala
(Lscala/Tuple2;ILjava/lang/String;)V
```

In order for the rewrite to work, we need to infer how many parameter lists are encoded into that signature in order to match them against the applied arguments. Unfortunately the signature doesn't have an obvious separator to break on.

We could think of parsing denotations instead, but I think at this point relying on compiler messages would be the way to go.

/cc @olafurpg

**Comment by gabro** [comment]
By the way, I've tried to improve the parsing using `sun.reflect.generics.parser.SignatureParser` but that yields a flat three-parameter list. The information of how many param list we're dealing with is simply lost in the encoding.

**Comment by gabro** [comment]
@xuwei-k #208 should fix this. We now use compiler messages so false positives should be near to impossible, while we may have some false negatives (i.e. rewrites not being applied), but that's much more acceptable.
