### ISSUE TITLE
Document scalacOptions for sbt-scalafix and explicitReturnTypes config

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#267]
Hey Olaf,

I tried to run scalafmt on the scaladex codebase. This is how it's configured:

https://github.com/scalacenter/scaladex/commit/f8dabd5eb66461c9e077dc90773294ee0874ebd9

The doc has mentioned I should configure this rewrite https://scalacenter.github.io/scalafix/#ExplicitReturnTypes

**Comment by MasseGuillaume** [comment]
I think the solution is to do this:

```
x.explicitReturnTypes {
   memberKind = [
     Def
     Var
     Val
   ]
   memberVisibility = [
     Public
     Protected 
  ]
}
```

**Comment by MasseGuillaume** [comment]
Also, unrelated to this issue. I ran RemoveUnusedImports. I see some unused import warning from the compiler, but they are not removed by scalafix.

**Comment by olafurpg** [comment]
I managed to reproduce your issue and the problem was that build.sbt sets `scalacOptions :=` instead of `++=`. By replacing `:=` with `++=` I was able to run the rewrites. Alternatively, the next release of sbt-scalafix exposes a `scalafixScalacOptions` setting which can be appended to `scalacOptions` if you prefer to keep `:=`. This is not documented so I'm gonna keep this issue open.
