### ISSUE TITLE
Load rewrite rules from resources

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scalafix#30]
This will allow projects to include their own rewrite rules specific to their project and allow library authors to export rewrite rules with their libraries.

**Comment by olafurpg** [comment]
Great idea! Some thoughts:

- we could publish `scalafix-testkit` which wraps the unit testing infrastructure in `scalafix-tests` into a reusable component. I think a good workflow for writing rewrites is important.
- loading rewrites from resources is a good idea so that libraries can include the rewrite in their published jar.
 
Question:
- How do we get a `Rewrite` instance given a source file? We have access to the compiler apis so we could compile a source file. We could have a convention that every method with "Rewrite" in it's name and an explicit return type "Rewrite" will be invoked.

**Comment by ShaneDelmore** [comment]
Could we skip making it an actual rewrite instance and just have it take a function from Tree => Seq[Patch]?

**Comment by olafurpg** [comment]
Yes, absolutely, but you'll need the ctx too. Question whether we shouldn't just put the tree into the RewriteCtx so the Signature is `RewriteCtx => Seq[Patch]`. I'm open for suggestions on alternative name for RewriteCtx.

This matches well with principle of least power http://www.lihaoyi.com/post/StrategicScalaStylePrincipleofLeastPower.html#static-methods-only I don't think we can avoid the custom types. 

It possible to create a rewrite from a function like this

```scala
object Rewrite {
  def apply(f: (Tree, RewriteCtx) => Seq[Patch]): Rewrite =
    new Rewrite {
      override def rewrite(code: Tree, ctx: RewriteCtx): Seq[Patch] =
        f(code, ctx)
    }
}
```

I like to create non-anonymous `Rewrite` classes because I like to open them in IntelliJ with "Enter class name" :)

**Comment by olafurpg** [comment]
btw, my thinking with RewriteCtx is to use it to bundle necessary values such so that you can `import ctx._` and have several implicits (mirror, tree, dialect, ...) in scope.

**Comment by olafurpg** [comment]
It's now possible to load rewrites by fully qualified names, see https://github.com/scalacenter/scalafix/blob/0703bd5ad113ba9880933f574e157f5e524773d4/scalafix-nsc/src/test/resources/checkSyntax/FqnRewrite.source#L2

The only missing piece to fix this issue is to

1.  dynamically compile a source file
2. load its classfiles
3. find the fully qualified name of the rewrite in the source file

**Comment by olafurpg** [comment]
Support to compiler rewrites from source was added in https://github.com/scalacenter/scalafix/pull/127/commits/f18bd69a5ffaf083a9a580114c9b09b074f19cf6

The ScalafixCompilerDecoder is able to compile and load a rewrite from a String, see
https://github.com/scalacenter/scalafix/blob/3418408463109a0b0d2232ec0897f9c433699bee/scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala

It loads rewrites using a URI scheme with support for protocols

- `file:/path.scala` local file path
- `http:/...` fetch code from the web

To close this issue, it should be possible to add support for the `resource` protocol: `resource:/myrewrite.scala`. See here how the `file://` protocol is supported https://github.com/scalacenter/scalafix/blob/3418408463109a0b0d2232ec0897f9c433699bee/scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala#L74

**Comment by olafurpg** [comment]
Is there still interest in loading rewrites from resources? Currently it's possible to load rewrites from

- classload from classpath
- source file on local file system (which compiles to classloader and classloaded)
- url (which gets downloaded to local file system
- github (which expands to url)

Adding support for loading source files from resources is super easy, but would it be used?

**Comment by ShaneDelmore** [comment]
We can close this.  I originally wanted it to be able to bundle upgrades with newer versions of libraries but I won’t be using it for at least a month so if I need it later I can add it then.
