### ISSUE TITLE
Proxy -Xlint warnings

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#357]
Now that we have a linter infrastructure, we can probably proxy a bunch of -Xlint warnings so that they are emitted directly by Scalafix and whatever infrastructure we may build on top of it (editor integrations and so on)

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
