### ISSUE TITLE
DisableSyntax.noSemicolons in the middle of expression

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#479]
when using DisableSyntax.noSemicolons = true

it could be helpful to spot copy-pastes from java code such as

```scala
val a = 1;
```

but it's sometimes useful:

```scala
for (v <- vectors; u <- vectors) {
```

it would be nice to allow the later.

**Comment by olafurpg** [comment]
Given that `for (v <- vectors; u <- vectors) {` can be written as
```scala
for {
  v <- vectors
  u <- vectors
}
```
I think it's fine to keep the current behavior, since you already opt into the rule.

The analysis to determine if a semicolon is otherwise non-trivial, semicolons may be used in tricky cases like

```scala
val x = 2;
{ y: Int => y + x}
```
where removing the semicolon will produce a different parse tree

```scala
val x = 2 { y: Int => y + x }
```
