### ISSUE TITLE
sbt bugs as observed in ensime-server

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#489]
1. if there are no scala files in the project (e.g. java project)  we get `scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8`
2. if I use `scalafixEnabled := false` in specific projects that I don't want to touch, the aggregated `scalafix RemoveUnusedImports` gives `scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8` in the disabled projects instead of skipping them

**Comment by olafurpg** [comment]
Good catch, thanks for reporting!

Pending fix for 1) in #490 

`scalafixEnabled` is a misnomer since what it currently means "do not automatically enable the semanticdb-scalac plugin". I agree `scalafixEnabled := false` should mean "`scalafix`does nothing". Is `disablePlugins(ScalafixPlugin)` a more idiomatic way to accomplish the latter? If so, then I propose we rename `scalafixEnabled` to `scalafixSemanticdbEnable`. I plan to make it false by default in 0.6, since I've found it difficult to make the automatic setup work for all builds.

**Comment by fommil** [comment]
actually you're right, I should be disabling the plugin and the proposed name sounds better.
