### ISSUE TITLE
ban orphan implicits

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#526]
https://github.com/wartremover/wartremover/issues/396

It would be good to exclude definitions of implicits `F[G]` unless they are on the companion of the `F` or the `G`. We might want to consider other HKT shapes too.

Of course, people can still opt out of this with the comment rules, but this makes it more obvious that they are doing something dangerous.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
