### ISSUE TITLE
ban things that break exhaustivity checks

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#528]
Some things **silently** break exhaustivity checking

- https://github.com/wartremover/wartremover/issues/382
- https://github.com/scala/bug/issues/10660
- pattern matching over unsealed things

we should detect when this occurs and make the user opt-in to broken checks.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
