### ISSUE TITLE
Useful rewriting for Dotty compatibility: add explicit result types to overriding members

### ISSUE THREAD

**Issue by smarter** [scalacenter/scalafix#551]
In Dotty, unlike Scala 2, the result type of an overridding member is always set to the result type of the overriden member instead of being inferred from the rhs. For example:
```scala
trait A {
  def foo: Any
}
class B extends A {
  override def foo = 1
  val x: Int = foo
    // error: found: Any, required: Int
    // This can be fixed by writing `override def foo: Int = 1`
}
```

It would be nice to have a rewriting to add result types to overriding members when the result type inferred by scalac differs from the result type of the overriden member.

**Comment by olafurpg** [comment]
This is a great idea! The ExplicitResultTypes rewrite still has a few bugs that need to be ironed out https://github.com/scalacenter/scalafix/issues/324 and we'll first need to fix https://github.com/scalameta/scalameta/issues/1209 as well.

**Comment by olafurpg** [comment]
Thanks for reporting @smarter ! I've recently closed all feature requests around new rule additions since custom rules can now be developed outside the scalacenter/scalafix repo and still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

We can discuss better in Lausanne how to get the ball moving on the the migration rewrites.
