### ISSUE TITLE
"Pattern var is never used" autofix

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#555]
I'm not sure about potential edge cases, but I think this is a pretty safe rewrite:

From:

```scala
opt match {
  case Some(x) => 42
//          ^
//          pattern var x in value $anonfun is never used; `x@_' suppresses this warning
}
```

to

```scala
opt match {
  case Some(_) => 42
}
```

Similarly:

```scala
try {
  whatever()
} catch {
  case e: SomeException => println("boom!")
}
```

to

```scala
try {
  whatever()
} catch {
  case _: SomeException => println("boom!")
}
```

Maybe this could be an optional feature of `RemoveUnused`

**Comment by som-snytt** [comment]
The reason `x @ _` suppresses the `-Xlint` warning is that the name is useful documentation. Instead of discarding the name, the rule should perform the recommended rewrite; or optionally discard it, or discarding for known container types.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
