### ISSUE TITLE
Rule idea: fix Octal escape literals

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#564]
```
[warn] /home/gui/re2/re2s/src/test/scala/re2s/CharClassSuite.scala:113: Octal escape literals are deprecated, use \u0000 instead.
[warn]                 Array('\0', Unicode.MAX_RUNE))
[warn]                        ^
```

A rule could easily fix `'\0'` to `'\u0000'`

**Comment by som-snytt** [comment]
There may be caveats. For example, `'\u000A'` used to be illegal in Scala 2, not sure about dotty.

**Comment by olafurpg** [comment]
After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
