### ISSUE TITLE
migration mode to add scalafix:ok instead of failing

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#599]
When enabling scalafix on an existing codebase, or introducing a new rule, it is often necessary to temporarily ignore rules until time can be set aside to clean the legacy code.

It would be very useful to be able to run a special scalafix task and have the necessary comments added automatically, such that a subsequent run of the scalafix task will succeed.

**Comment by vovapolu** [comment]
Should it put `scalafix:ok` to prevent rewriting? Or only on linter errors?

**Comment by fommil** [comment]
just linter errors

**Comment by olafurpg** [comment]
Should we generically implement this for all rules or if linter rules should provide rewrites to disable each message under a specific flag? I'm personally inclined for the second option since rules have access to trees which means then can target the comments more precisely. Linter messages have only a `Position`, we could blindly put a `// scalafix:ok` at the end of those lines but it might not work perfectly in all cases.

**Comment by olafurpg** [comment]
Fixed in #646
