### ISSUE TITLE
RemoveUnusedImports does not handle wildcard imports correctly.

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scalafix#614]
If I have the code
```
import scala.util.{Try => UnusedTry, _}
```
and UnusedTry is actually unused, then rewriting the code to 
```
import scala.util._ 
```
does not actually remove the import.  

A better rewrite here would be to explicitly unimport
```
import scala.util.{Try => _, _}
```

**Comment by ShaneDelmore** [comment]
Specifically, after running unused imports on a large codebase I found many users are using renames where they should be using unimports.  This caused compilation failures after running RemoveUnusedImports.  The minimum to have a RemoveUnusedImport that doesn’t break compilation would be just to unimport the unused rename.

**Comment by olafurpg** [comment]
You are right, unimporting is the only option to avoid rewriting into code that no longer compiles. This is a bug.

**Comment by som-snytt** [comment]
Unused import really means an unused selector on an import clause, not "a symbol you could look up in scope but neglect to."

I'll take a look for my first scalafix. Wish me luck. I'd like a rule for the precedence change in 2.13, where an import now shadows a definition from a package you're in (and the definition is not from the current source file).

For example,
```
// a.scala
package p { class C }
package q { class C }
// b.scala
package p { import q._ ; class X extends C }
```
used to be `X extends p.C` but will be `q.C` because that's what you wrote.

The fix is to rewrite the import to not shadow: `import q.{C => _, _}`. This is a migration fix, but it also strikes me as a good idea not to willfully exploit this precedence, which protects you if someone adds a new definition `p.C`, but is confusing for a reader later to guess which `C` is intended. So the rewrite should live on as a lint warning. If someone refactors `q.C` to `p.C` but doesn't delete the original (because maybe it's just a cut and paste), lint should warn you.

**Comment by som-snytt** [comment]
Thanks, I'll know more when I can spend some time with the projects. They've said "when we have a rewrite tool" for so long, and now I really need it. :sweat_smile:

**Comment by olafurpg** [comment]
PR fixing this issue https://github.com/scalacenter/scalafix/pull/833
