### ISSUE TITLE
Require all built-in rewrites to respect // scalafix: off

### ISSUE THREAD

**Issue by Mharlin** [scalacenter/scalafix#622]
When running semantic rules the exclusion comments like `// scalafix:off` or `scalafix:ok` are ignored and the rules are applied anyway.

On the positive side it tells you in the output that it has ignored the exclusion comments.

**Comment by olafurpg** [comment]
Thank you for reporting! Can you please include which rules don't respect the exclusion comments? Currently, rules opt-into supporting this functionality by documenting which patches should atomically be applied together.

**Comment by Mharlin** [comment]
The only rule that I have tried it for is MissingFinal.

**Comment by olafurpg** [comment]
This ticket can be fixed in two steps

* [ ] use .atomic in all built-in scalafix rewrites (easy)
* [ ] update testkit to fail if a rewrite does not use `.atomic` (more advanced). This involved validating `patch` below contains `Atomic` nodes

https://github.com/scalacenter/scalafix/blob/dcaa5320321972aa99f0683176c6e759a83b5f8b/scalafix-testkit/src/main/scala/scalafix/testkit/SemanticRuleSuite.scala#L82

**Comment by olafurpg** [comment]
`MissingFinal` has now been moved to a separate repo and all scalafix rules have been updated to use `.atomic`. I'm not sure if it's a good idea anymore to assert in testkit that all patches are wrapped in `.atomic` so I think the current behavior is fine.
