### ISSUE TITLE
Use Build Stages in Travis

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#623]
We can simplify the travis bulid with build stages: 
https://docs.travis-ci.com/user/build-stages/#Deploying-to-NPM

* wait for all test
* publish to Sonatype

Currently, the test can fail in 2.11 but we would still publish to Sonatype.

**Comment by olafurpg** [comment]
The release pipeline is working robustly and hasn't caused much problems since we publish all modules from the same Travis job. We use the same setup in scalameta/scalameta as we have in the scalafix build. Let's pick this up again if releasing becomes a problem that can be fixed with travis build stages.
