### ISSUE TITLE
restrict pattern matcher to enforce exhaustivity

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#636]
https://github.com/wartremover/wartremover/issues/382

The scala compiler will perform exhaustivity checks when matching on
sealed traits, e.g.

```
scala> sealed trait Foo
       final case class Bar(flag: Boolean) extends Foo
       final case object Baz extends Foo

scala> def thing(foo: Foo) = foo match {
         case Bar(_) => true
       }
<console>:14: error: match may not be exhaustive.
It would fail on the following input: Baz
       def thing(foo: Foo) = foo match {
                             ^
```

However, the compiler will not perform exhaustivity checking if there are guards, e.g.

```
scala> def thing(foo: Foo) = foo match {
         case Bar(flag) if flag => true
       }

/// NOTE NO WARNING!!!!

scala> thing(Baz)
scala.MatchError: Baz (of class Baz$)
  at .thing(<console>:15)
```

Thus, guards should not be allowed when matching on a `sealed trait`.

See https://github.com/scala/scala/pull/5617 for `-Xstrict-patmat-analysis`

**Comment by olafurpg** [comment]
I am open to refine this RFE to add a setting `DisableSyntax.noCaseGuardsWithoutFallback = true` that prohibits usage of case guards without a blank `_` fallback pattern.

If you want the analysis to be more advanced, I think this feature is best solved by changing the compiler exhaustivity checker to pessimistically assume guards always evaluate to false. There's a discussion in https://github.com/scalacenter/scalafix/issues/636 about reviving the PRs adding stricter pattern matching analysis, I recommend to push on that side instead of adding custom scalafix linter rules. 

Alternatively, if someone wants to implement this analysis with scalafix they always can implement a custom rule.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
