### ISSUE TITLE
Disable.unlessSynthetic.safeBlock should support a list of symbols

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#649]
the following config

```
Disable.unlessInside = [
    {
        safeBlock = "scalaz.effect.IO.apply"
        symbols = [
          "java.lang.System.currentTimeMillis"
        ]
    }
]
```

will error on the following

```
      IO {
        java.lang.System.currentTimeMillis()
      }
```

because this IO is defined in a custom `Predef` as

```
package std {
  val IO = scalaz.effect.IO
}
```

But the symbol `std.IO` should have been dealiased to `scalaz.effect.IO.apply` and this rule would have said OK to the block.

**Comment by olafurpg** [comment]
what happens if you make it?

```scala
IO.apply {
  java.lang.System.currentTimeMillis()
}
```

It could be that the handling for inferred .apply is the culprit here.

**Comment by fommil** [comment]
@olafurpg I was just about to say that! I noticed that using `std.IO.apply` was causing me troubles. In either case, it's a lack of dealiasing to blame.

**Comment by olafurpg** [comment]
Method symbols and vals can't be dealiased. `val IO = scalaz.effect.IO` is not a type alias. However, I'm planning to give val forwarders like that a first-class representation in semanticdb via `AliasDefinition`, see https://github.com/scalameta/scalameta/issues/1386 

I suspect the problem is how the `apply` is handled in the rule implementation https://github.com/scalacenter/scalafix/blob/67a1f287618ad11144e85af3d79a3c240e0268de/scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala#L110
The correct way to detect which `.apply` symbol is used would be to lookup the resolved symbols in synthetics. It's a bit awkward to do with the current API.

A workaround for this problem for now is to explicitly list all val forwarders.

**Comment by fommil** [comment]
cool, no problem. I'll probably create two lists:

- things that should always be banned
- things that can only run inside an `IO`

and I'll just reference them from the various `Disable` / `NoInfer` rules multiple times.

**Comment by olafurpg** [comment]
Working as intended. `val A = foo.A` is not a type alias. A workaround for this problem for now is to explicitly list all val forwarders. I'm happy to consider making this more intuitive if someone wants to work on improving this situation.

**Comment by fommil** [comment]
the workaround doesn't work because we can't list multiple things. Consider

https://github.com/scalaz/scalazzi/blob/master/scalafix.conf#L110-L111

I'd be happy with this as a workaround... but it's not really feasible to copy the entire `Disable.unlessInside` / whatever rule for each thing.

**Comment by olafurpg** [comment]
I see, I've updated the title to be about making it possible to list multiple symbols as a safeBlock

```
Disable.unlessInside = [
    {
        safeBlock = ["scalaz.effect.IO", "std.IO"]
        symbols = [
          "java.lang.System.currentTimeMillis"
        ]
    }
]
```

**Comment by olafurpg** [comment]
Moved to https://github.com/vovapolu/scaluzzi/issues/3
