### ISSUE TITLE
RemoveUnusedImports with comma-separated imports

### ISSUE THREAD

**Issue by NeQuissimus** [scalacenter/scalafix#653]
I have a line of imports like so:

```scala
import eu.timepit.refined, refined.api.Refined, refined.string._, refined.auto._, refined.collection._
```

Now imagine `eu.timepit.refined.string._` is unused.

Unfortunately, Scalafix is a little eager in removing characters it seems as it turns the above into the following:

```scala
import eu.timepit.refined, refined.api.Refinedrefined.auto._, refined.collection._
```

I have to manually place back a comma (and space) or (what I am going to do now) keep the imports on separate lines altogether.

**Comment by olafurpg** [comment]
Thanks for reporting! I was able to reproduce in https://github.com/scalacenter/scalafix/compare/master...olafurpg:653?expand=1 I will take a look into fixing this once v0.6.0 is out!

**Comment by olafurpg** [comment]
Sorry for how long this took! It was a bit tricky to fix since the implementation for removing commas is a bit hairy 😅 In theory it should be simple but when you constrain yourself to only remove tokens (not possible to remove all imports and synthesize the used imports) then it's harder to handle combinations of multiple importers `import a.b, c.d` and importees `import a.{b, c, d}`. Trailing commas make it even trickier :)

This will be included in the next release :)
