### ISSUE TITLE
Rewrite view bound

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#753]
https://github.com/scala/scala/releases/tag/v2.13.0-M4 (https://github.com/scala/scala/pull/6500)

input:
```scala
def f[T <% Map[Int, Int]](x: T): Double = 1.0d
```
output:
```scala
 def f[T](x: T)(implicit ev: T => Map[Int, Int]): Double = 1.0d
```

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
