### ISSUE TITLE
warning if a directory contains a dot

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#765]
directory names such as https://github.com/scalacenter/accessible-scala/blob/master/cli-args/src/main/scala/ch.epfl.scala.accessible/CliOptions.scala

cause big confusions for tools, e.g. as described in https://github.com/scalacenter/advisoryboard/blob/master/proposals/011-debugging-symbols.md

It would be good to detect this and issue a warning.

This is a kind of novel rule in the sense that it applies to the filename, not its contents! This may not have been considered in the API design.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
