### ISSUE TITLE
rule: AnyVal in tuple

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#799]
tuples will always box a primitive value. It is always more efficient to create a custom case class to hold a primitive value. It would be good to have a linter rule to catch when people put primitives in tuples.

**Comment by MasseGuillaume** [comment]
@fommil This is a good idea, however, this rule is really specific. Our goal is to reduce the number of built-in rules to make the maintenance easier.

**Comment by fommil** [comment]
at this point I'm assuming this issue tracker is the central place for ideas to spawn of community focused rules. Maybe somebody will want to create a set of performance rules.

**Comment by MasseGuillaume** [comment]
@fommil maybe we should create a scalafix organization and add a `scalafix-community-rules` repo for this.

**Comment by fommil** [comment]
tomorrow is my last day as a Scala developer, so I don't really care :laughing: but my two cents are that you shouldn't bother spinning off "community" repos or forums until the community is big enough to need it. There are less than 10 people interested in scalafix right now (which will change when it is stable) so I recommend just centralising everything until the burden gets too big on the core devs.

**Comment by olafurpg** [comment]
This is an interesting idea. @MasseGuillaume is right that we are moving towards improving support for 3rd party rules  instead of adding everything into the scalafix repo. This issue tracker is a fine place for now, I agree with @fommil the interest atm is too small to spread issues across multiple repos. Heads up though, we may mass-close these ideas at some point with a "community" label or similar.

**Comment by fommil** [comment]
Given that I officially don't write Scala anymore, I don't care :-P

**Comment by olafurpg** [comment]
After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
