### ISSUE TITLE
Rewrite creates unused imports

### ISSUE THREAD

**Issue by paulp** [scalacenter/scalafix#83]
The import rewriter transforms this, which compiles:
```scala
package a

import scalaz.Scalaz, Scalaz._

package object b {
  5.some
}
```
into this, which does not - at least, not if you're using our compiler options, because it creates an unused import where there was no unused import and `-Xfatal-warnings` steps in.
```scala
package a

import scalaz.Scalaz
import scalaz.Scalaz._

package object b {
  5.some
}
```

**Comment by olafurpg** [comment]
Thanks for reporting! I was aware of this issue, which is esp. problematic when using `-Ywarn-unused-imports`. In order to handle this case, it seems necessary to either

- re-implement the symbol usage tracking,
- run the rewrites at least twice, or
- give up on expanding relative imports

Currently, scalafix uses `-Ywarn-unused-imports` to remove unused imports but `scalaz.Scalaz` becomes unused only after the rewrite.

**Comment by ShaneDelmore** [comment]
Rerunning the import rewrites until they stabilize seems like an easy fix if we can't easily handle them in one pass.

**Comment by paulp** [comment]
@olafurpg When you say `re-implement the symbol usage tracking` what is the `re-` a reference to? Do you mean reimplement your existing implementation, as in rewrite it? Or do you mean reimplement the compiler logic, suggesting you're not already tracking symbols? These rewrites can't possibly be purely syntactic, can they?

Just in case... rewriting imports without knowing what they mean will never work and could never have worked.

**Comment by olafurpg** [comment]
> these rewrites can't possibly be purely syntactic, can they?

No they are not purely syntactic, we are using the scala.meta semantic api to query for the symbols of importers.

> Or do you mean reimplement the compiler logic, suggesting you're not already tracking symbols? 

My first attempt to track usage of symbols failed because of several challenges

- macros, some imported symbols reference macros that expand to literal
- language imports, those imported symbols are not present the compilation unit
- long tail of random stuff like annotations that are imported+used but a plain traverser will not visit in the compilation unit without ad-hoc workarounds (e.g., `TypeTree.origin`).

After bumping into all of these problems, I changed the strategy to use `-Ywarn-unused-imports` to determine which imports can be removed. The only case where I've seen this strategy fail so far is this particular issue when a relative import is expanded, making a previous import become unused.

The main objective of the "organize imports" feature in scalafix is to support the `Add/RemoveGlobalImport` tree patches, which are used by some rewrites like `ExplicitImplicit` to shorten fully qualified types. I think it's fine to not support the ability to expand relative imports, or support the feature with the caveat that you need to run rewrites twice to avoid "unused import" warnings.

> Just in case... rewriting imports without knowing what they mean will never work and could never have worked.

Thank you for pointing that out @paulp

**Comment by paulp** [comment]
> Thank you for pointing that out

he says, smiling through gritted teeth...

Thanks for the explanation. You have a great attitude, I'm sure it will take you far. (And since when I say something like that the recipient usually thinks I'm being sarcastic, I will preemptively clarify that I am 100% serious.)

**Comment by olafurpg** [comment]
I've disabled expanding relative import expansion by default. Those who choose to enable the flag do so at the risk of creating unused imports. The unused imports created by the rewrites can be removed by running scalafix twice.

I'll keep this issue open if someone is interested in contributing a fix so that expanded relative imports clean up unused imports created by the expansion. Note, however, that will probably involve dealing with tricky cases like imports on macros, as explained here https://github.com/scalacenter/scalafix/issues/83#issuecomment-284365646
