### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by evis** [scalacenter/scalafix#901]
It would be nice to have maven support. There are still a lot of scala projects built using maven.

Though, issue #726 have some info about trying to run scalafix on maven project. And there is even such link to maven installation docs: https://scalacenter.github.io/scalafix/docs/users/installation#maven but sadly, there is actually no info about maven installation :(

**Comment by olafurpg** [comment]
Thanks for reporting! The maven installation instructions were removed because they got outdated in the new v0.9 release. Scalafix now requires --classpath to include the full classpath of the project, including dependencies, so I believe it is best to implement a proper Maven plugin instead of use the command-line interface (as the. I am not familiar with Maven plugin development but to implement a scalafix plugin you need access to the following

- plugin should depend on `scalafix-interfaces` module that is a pure Java API (8kb jar) designed for build tools https://static.javadoc.io/ch.epfl.scala/scalafix-interfaces/0.9.0/index.html
- full classpath of the `scalafix-cli_2.12.7` module that is passed to the static method `scalafix.interfaces.Scalafix.classloadInstance(ClassLoader): Scalafix` to get an instance of Scalafix API. Here is how the API is used by sbt-scalafix https://github.com/scalacenter/sbt-scalafix/blob/a3c4bf2444b47cd76103964487b3dc6885403673/src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala#L20-L37

Once you have a `ScalafixArguments` instance you can construct invocation with a fluent API
```scala
val arguments: ScalafixArguments = ...
val errors: Array[ScalafixError] = arguments
  .withPaths(List<nio.file.Path>)
  .withClasspath(List<nio.file.Path>)
  .run()
```

**Comment by niebloomj** [comment]
Any updates on this?

**Comment by evis** [comment]
I'm working on this, hope to release plugin in June :)

**Comment by evis** [comment]
https://github.com/evis/scalafix-maven-plugin/ released, you can try it :) 

todo: add link to Maven plugin in Scalafix docs
