### ISSUE TITLE
error fix :remove unsed

### ISSUE THREAD

**Issue by He-Pin** [scalacenter/scalafix#914]
before :
```
    private var upstreamFailed: OptionVal[Throwable] = OptionVal.None

```
after 
```
    OptionVal.None

```

source :akka.stream.impl.fusing.ActorGraphInterpreter.ActorOutputBoundary

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/49330168-f904bd80-f5c5-11e8-957b-b56e23aee9d8.png)

**Comment by marcelocenerine** [comment]
@hepin1989, looks like this behavior is intentional (see tests: [input](https://github.com/scalacenter/scalafix/blob/master/scalafix-tests/input/src/main/scala/test/RemoveUnusedTerms.scala#L10) / [output](https://github.com/scalacenter/scalafix/blob/master/scalafix-tests/output/src/main/scala/test/RemoveUnusedTerms.scala#L7)). The reason is that the the LHS of an assignment may contain side effects. Thus, removing the entire line could change the behavior of the program. However, if the LHS of the assignment is a literal, then the rule removes the entire thing.

**Comment by hepin1989** [comment]
@marcelocenerine after you remove that ,Akka did not compile:)

**Comment by olafurpg** [comment]
@hepin1989 what is the resulting compile error?

We can probably remove the right-hand side if it only references vals. We can try to reproduce what the compiler does

**Comment by marcelocenerine** [comment]
sorry, I meant RHS in my previous comment.

**Comment by marcelocenerine** [comment]
The following causes a compiler error:

- Input:
```
  private val opt: Option[String] = None
  private val num: Integer = { println("foo"); 1 }
```

- Output:
```
  None
  { println("foo"); 1 }
```
```
None.type does not take parameters
[error]   { println("foo"); 1 }
[error]   ^
```

**Comment by olafurpg** [comment]
Aah yes :) that is a good test case! Thank you @marcelocenerine

**Comment by hepin1989** [comment]
@olafurpg could not find the symbol.

**Comment by hepin1989** [comment]
@olafurpg I only make use of scalafix for remove the unused import now.the problem presents when I use the default settings.
