### ISSUE TITLE
Support linters, rewrites that only emit info/warn/error messages

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scalafix#92]
without the rewrite part, a rewrite rule becomes a linter rule, and Scalafix becomes a linter too.

I started a discussion on this possibility at https://contributors.scala-lang.org/t/whats-the-status-of-abide/609

**Comment by ShaneDelmore** [comment]
Interesting thought. Not sure if this is in scope but to continue with the idea, if we separated out generating rewrites from applying rewrites then it becomes a linter with a possible auto-fix. If someone catches exception, we could warn, and if they ran autofix --rewriteName we could automatically rewrite to case NonFatal... for example.

**Comment by olafurpg** [comment]
@SethTisue I just opened https://github.com/scalacenter/scalafix/pull/118 which adds support for rewrites to report info/warn/error messages to users. I think the next steps to add support for linters would be to

- Add a `Linter` class which returns `Seq[Message(msg, severity, position)]` instead of `Seq[Patch]`
- Change cli exit code depending on linter warnings/errors
- Add a `fatalWarnings: Boolean` configuration option, which promotes warning messages to error, just like the Scala compiler.

**Comment by ShaneDelmore** [comment]
@olafurpg Regarding the linter, what do you think about having linters return  Seq[Message -> Seq[Patch]] to allow pairing patches with rewrites in case the user wants to fix them with Scalafix?  Say for the case of a deprecation warning or missing import?

**Comment by ShaneDelmore** [comment]
Linter rule authors would not have to write patches, but if they decided to much of the code might be shared.

**Comment by olafurpg** [comment]
Good idea @ShaneDelmore 

We might even want use such a data structure (name is open) for normal rewrites

```scala
Observation(message: String, patches: Seq[Patch])
```

since I think it's useful to attach messages to rewrites as well. It's been awhile since I looked at what they do in similar tools such as clang-tidy, rustfix. I'm sure we can get inspiration from them.

**Comment by olafurpg** [comment]
It should be possible to accommodate linters with the current API. Rewrites have access to `ctx.reporter` which is a similar api as `g.reporter` in scalac, see https://github.com/scalacenter/scalafix/blob/db6152304aaef19c4a8ba4fc77b732264bf52fec/scalafix-core/src/main/scala/scalafix/config/ScalafixReporter.scala#L36-L40

Info, warning and error messages are printed to the console. The remaining parts to close this issue is to make sure that the scalafix cli exits with a non-zero exit status in case errors are reported. 

- [ ] add a `hasErrors` method to ScalafixReporter which returns true if an error has been reported. This method should be thread safe since the same reporter may be used across multiple threads, I would recommend to use an `AtomicReference`.
- [ ] Add LinterError exit status https://github.com/scalacenter/scalafix/blob/db6152304aaef19c4a8ba4fc77b732264bf52fec/scalafix-cli/src/main/scala/scalafix/cli/ExitStatus.scala#L30
-  [ ] query `config.reporter` after running CliRunner to see if any errors occurred  and merge that exit status with the accumulated exit status https://github.com/scalacenter/scalafix/blob/db6152304aaef19c4a8ba4fc77b732264bf52fec/scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala#L77

This is one fairly lazy way to reach this goal. Using the same mutable reporter across multiple threads may be problematic.

Alternatively, it may be better to encode linter messages in the `Patch` system. For example, we could be add a custom `scalafix.patch.Message(p: Patch)` type which can be used to enrich both regular non-empty patches as well as `Patch.empty` with an error message. This would require us to rethink the `Rewrite.apply/diff` api, however.

**Comment by olafurpg** [comment]
After some thinking about how to support this, there are a few more things to keep in mind

- escape hatches (ignore warning at this location), related #241.
- message IDs. Each reported linter message should have an associated ID. One "Linter" can report multiple kinds of messages. It should be possible to configure scalafix to exclude messages of a particular ID.

**Comment by olafurpg** [comment]
Just opened a WIP PR for this here https://github.com/scalacenter/scalafix/pull/291 In particular, I'm interested to get some feedback on the ideas explained in this commit here https://github.com/scalacenter/scalafix/pull/291/commits/8810e25968161f9a8e27a577d673c8b844a0540f

**Comment by olafurpg** [comment]
Support for linters was added in #291. Docs on how to emit lint messages are here https://scalacenter.github.io/scalafix/#LintMessage End users can override the severity level of lint messages with https://scalacenter.github.io/scalafix/#lint

I'm gonna close this issue as fixed. I am happy to iterate on the lint API, please report back your experience :)
