### ISSUE TITLE
Provide a mechanism to enforce named arguments on the invocations of certain methods

### ISSUE THREAD

**Issue by tanin47** [scalacenter/scalafix#945]
Hi, I'm coming from this reddit thread: https://www.reddit.com/r/scala/comments/aq2bt6/just_made_a_compiler_plugin_to_enforce_named/

I've made a compiler plugin that enables us to force use named arguments on the invocation of certain methods (https://github.com/GIVESocialMovement/scala-named-argument-compiler-plugin). We allow user to specify the annotation for marking through `scalacOptions`. The plugin builds the data during the `parser` phase and read that data in the `typer` phase.

The user 'olafurpg' (who is a maintainer of this repo) mentioned that this might fit well with scalafix's vision, and I'd love to integrate it into scalafix instead of having my own standalone compiler plugin.

I wonder how the API should look like if we integrate this feature into scalafix?

**Comment by olafurpg** [comment]
Thanks for reporting! This feature can be developed separately as a custom rule, it would not go into the Scalafix repository itself. The tutorial here https://scalacenter.github.io/scalafix/docs/developers/tutorial.html shows the steps from testing, adding configuration and publishing. The tutorial covers a similar example (named arguments) so that can be helpful for you too. If you have questions about how to use the Scalafix API, feel free to ask in Gitter :) http://gitter.im/scalacenter/scalafix

**Comment by tanin47** [comment]
Oh, I see. I misunderstood that. Thank you for the clarification.
