### ISSUE TITLE
ExplicitResultTypes not documented on the website

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scalafix#987]
`ExplicitResultTypes` is present as a built-in rule
https://github.com/scalacenter/scalafix/blob/master/scalafix-rules/src/main/resources/META-INF/services/scalafix.v1.Rule
https://github.com/scalacenter/scalafix/blob/master/scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala

but isn't documented on the website
https://scalacenter.github.io/scalafix/docs/rules/overview.html

**Comment by olafurpg** [comment]
Thank you for reporting! This rule is intentionally not documented on the website since it doesn't work correctly. The rule is excluded from tab completions as well to prevent users from accidentally discovering the rule. I was close to removing the rule from the codebase but kept it because we are already using it in test suites in external repositories like https://github.com/scalacenter/sbt-scalafix
